---

kind: pipeline
name: default

steps:
  - name: Update Nginx Server
    image: appleboy/drone-ssh
    settings:
      host: 192.168.1.26
      username:
        from_secret: username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /var/www/html/personal_website
        - git pull
        - nginx -s reload